// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import "./globals.css"
import ClientSessionProvider from "@/components/ClientSessionProvider"; // Import the client component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <ClientSessionProvider>
                        {children}
                        <Toaster />
                    </ClientSessionProvider>
                </div>
            </body>
        </html>
    );
}
